name: pod_player
description: Vimeo and youtube player for flutter, Pod player provides
  customizable video player controls that support android, ios and web.
version: 0.2.1
homepage: https://github.com/newtaDev/pod_player

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_video_player:
    git:
      url: https://github.com/AnasAltaleb/flutter_cached_video_player.git


  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.1.0
  universal_html: ^2.2.3
  # video_player: ^2.7.0
  wakelock_plus: ^1.1.1
  youtube_explode_dart:
    git: https://github.com/MohanadDaDev/youtube_explode_dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

screenshots:
  - description: Pod video player logo
    path: screenshots/logo.png
